---
- name: Copy the Infra creation scripts
  hosts: ec2
  tasks:
      - name: Executing the scripts
        become: true
        command: /tmp/configure_mysql_aws.sh 
      
      - name: Configuring mediawiki
        become: true
        command: /tmp/install_mediawiki_aws.sh
        