---
- name: Copy the Infra creation scripts
  hosts: ec2
  tasks:
      - name: copying script files to remote host
        become: true
        copy: src={{ item.src }} dest={{ item.dest }}
        with_items: 
            - { src: '../install_dependencies_aws.sh',  dest: '/tmp/' }
        mode: +x
        