---
- name: Copy the Infra creation scripts
  hosts: ec2
  tasks:
      - name: copying script files to remote host
        become: true
        copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
        with_items: 
            - { src: '../install_dependencies_aws.sh',  dest: '/tmp/install_dependencies_aws.sh', mode: +x}
            - { src: '../configure_mysql_aws.sh',  dest: '/tmp/configure_mysql_aws.sh', mode: +x}
            - { src: '../install_mediawiki_aws.sh',  dest: '/tmp/install_mediawiki_aws.sh', mode: +x}


        
        